# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'github-issues-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'  

  # Pods for github-issues-iOS

  target 'github-issues-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'github-issues-iOSUITests' do
    # Pods for testing
  end

end
